version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    groups:
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
        - "botframework*"
        - "powerbi*"
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
        - "botframework*"
        - "powerbi*"
      botframework:
        patterns:
        - "botframework*"
      powerbi:
        patterns:
        - "powerbi*"
  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10