name: Bump APIVersion in pbiviz.json on powerbi-visuals-api update
on:
  pull_request_target

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # newVersion cannot be retrieved with grouped updates. Falling back to JSON reading.
      # See https://github.com/dependabot/fetch-metadata/issues/402
      # - name: Retrieve apiVersion from package update
      #   id: version
      #   if: "contains(steps.metadata.outputs.dependency-names, 'powerbi-visuals-api')"
      #   run: |
      #     version_number="$(echo '${{ steps.metadata.outputs.updated-dependencies-json }}' | jq '.[] | select(.dependencyName=="powerbi-visuals-api") | .newVersion')";
      #     echo apiVersion: $version_number
      #     echo "apiVersion=$version_number" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        if: "contains(steps.metadata.outputs.dependency-names, 'powerbi-visuals-api')"

      - name: Retrieve package.json file to retrieve new version number
        id: version
        if: "contains(steps.metadata.outputs.dependency-names, 'powerbi-visuals-api')"
        run: |
          api_version_number="$(jq -c '.dependencies["powerbi-visuals-api"]' < package.json)"
          echo $api_version_number
          version_number=$(echo "$api_version_number" | sed 's/\~//g')
          echo apiVersion: $version_number
          echo "apiVersion=$version_number" >> $GITHUB_OUTPUT
          
      - uses: actions/setup-node@v4
        if: "contains(steps.metadata.outputs.dependency-names, 'powerbi-visuals-api')"
        with:
          node-version-file: 'package.json'

      - name: Update pbiviz.json apiVersion to new package version (powerbi-visuals-api)
        uses: jossef/action-set-json-field@v2
        if: "contains(steps.metadata.outputs.dependency-names, 'powerbi-visuals-api')"
        with:
          file: pbiviz.json
          field: apiVersion
          value: "${{ steps.version.outputs.apiVersion }}"

      - name: Extract branch name
        if: "contains(steps.metadata.outputs.dependency-names, 'powerbi-visuals-api')"
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Commit changes
        if: "contains(steps.metadata.outputs.dependency-names, 'powerbi-visuals-api')"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pbiviz.json
          git commit -m "Bump apiVersion to ${{ steps.version.outputs.apiVersion }}."
          git push origin HEAD:${{ steps.extract_branch.outputs.branch }}
