name: Package Power BI visual (PR)

on:
  pull_request:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Retrieve pbiviz.json file to retrieve version number
        run: echo "PBIVIZ_JSON=$(jq -c . < pbiviz.json)" >> $GITHUB_ENV

      - name: Update pbiviz.json version to include PR number
        uses: jossef/action-set-json-field@v1
        with:
          file: pbiviz.json
          field: visual.version
          value: "${{ fromJson(env.PBIVIZ_JSON).visual.version }}beta#${{ github.event.pull_request.number }}"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies (CI)
        run: npm ci

      - name: Package Power BI visual
        run: npm run package

      - uses: actions/upload-artifact@v2
        with:
          name: custom-visual-test-version
          path: dist/*.pbiviz
          if-no-files-found: error

