name: Package Power BI visual

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
    
      # Retrieve new version to tag and publish release with
      - name: Retrieve version from tag name
        id: version
        run: |
          tag=${{ github.event.release.tag_name }}
          version_number=${tag#?}
          echo version: $version_number
          echo "::set-output name=version::$version_number"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Bump package.json version to release version
        run: |
          npm version ${{ steps.version.outputs.version }} --no-commit-hooks --no-git-tag-version

      - name: Update pbiviz.json version to release version
        uses: jossef/action-set-json-field@v1
        with:
          file: pbiviz.json
          field: visual.version
          value: ${{ steps.version.outputs.version }}
          
      - name: Commit changes
        run: |
          git add package.json pbiviz.json

          git commit -m "Bump version to ${{ steps.version.outputs.version }}."
          git tag -f -a ${{ github.event.release.tag_name }}
          git push 
          git push origin -f ${{ github.event.release.tag_name }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies (CI)
        run: npm ci

      - name: Package Power BI visual
        run: npm run package

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.pbiviz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
